[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "capstone_imperial_ml_ai"
dynamic = ["version"]
description = "Imperial BS ML + AI Capstone Project"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
  { name = "jamichel" },
]

dependencies = [
  "pandas[pyarrow]",
  "polars",
  "scipy",
  "statsmodels",
  "scikit-learn",
  "ydata-profiling[notebook]",
  "dtale",
  "seaborn",
  "jupyter-contrib-nbextensions",
  "ipykernel>=7.1.0",
  "httpx>=0.28.1",
]

[project.urls]
Documentation = "https://github.com/ja-michel/capstone_imperial_ml_ai#readme"
Issues = "https://github.com/ja-michel/capstone_imperial_ml_ai/issues"
Source = "https://github.com/ja-michel/capstone_imperial_ml_ai"

[tool.hatch.build]
include = [
    "src/ml"
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/ml/_version.py"


[tool.coverage.run]
source_pkgs = ["src/ml", "tests"]
branch = true
parallel = true
omit = [
  "src/ml/__version__.py",
]

[tool.coverage.paths]
ml = ["src/ml"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
extend-exclude = [
  "*.txt",
  "*.md",
  "*.rst",
  "*.ipynb",
]
